version: '3'
volumes:
  tmp:
services:
  uvd:
    container_name: uvd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/../:/app
      - ~/.Xauthority:/root/.Xauthority
      - tmp:/app/.venv
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    runtime: nvidia
